@startuml context
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person_Ext(visitor, "Visitor", "A job seeker searching for jobs.")
Person(employer, "Employer", "An employer that wants to post a job.")
System(asj, "Algeria Startup Jobs System", "Allows visitors to search for jobs.\nAllow Employers to submit job posts.")
System_Ext(es, "E-mail system", "The internal NameCheap email system.")

Rel(visitor, asj, "Search for jobs in", "HTTPS")
Rel(employer, asj, "Submit job offer to", "HTTPS")
Rel(es, employer, "Sends e-mails to")
Rel(asj, es, "Uses", "SMTP")

@enduml
