name: Deploy To Production Environment

on:
  # pull_request:
  push:
  #   tags:
  #     - "v*"

jobs:
  Deploy-Diagrams:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn
      - name: "Build docs"
        run: |
          yarn build

        env:
          CI: true
